server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
#    schema: classpath:schema-h2.sql
#    data: classpath:data-h2.sql
logging:
  level:
    root: INFO
    org.hiberate: INFO
    org.hiberate.type.descriptor.sql.BasicBinder: TRACE
    org.hiberate.type.descriptor.sql.BasicExtractor: TRACE
